# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

varner <- function(ni, X, Y, method) {
    .Call(`_saeMSPE_varner`, ni, X, Y, method)
}

mspeNERdb <- function(ni, X, Y, Xmean, K = 50L, C = 50L, method = 2L) {
    .Call(`_saeMSPE_mspeNERdb`, ni, X, Y, Xmean, K, C, method)
}

mspeNERjack <- function(ni, X, Y, Xmean, method = 2L) {
    .Call(`_saeMSPE_mspeNERjack`, ni, X, Y, Xmean, method)
}

mspeNERmcjack <- function(ni, X, Y, Xmean, K = 50L, method = 2L) {
    .Call(`_saeMSPE_mspeNERmcjack`, ni, X, Y, Xmean, K, method)
}

mspeNERpb <- function(ni, X, Y, Xmean, K = 50L) {
    .Call(`_saeMSPE_mspeNERpb`, ni, X, Y, Xmean, K)
}

mspeNERsumca <- function(ni, X, Y, Xmean, K = 50L, method = 2L) {
    .Call(`_saeMSPE_mspeNERsumca`, ni, X, Y, Xmean, K, method)
}

mspeFHdb <- function(Y, X, D, K = 50L, C = 50L, method = 2L) {
    .Call(`_saeMSPE_mspeFHdb`, Y, X, D, K, C, method)
}

mspeFHjack <- function(Y, X, D, method = 2L) {
    .Call(`_saeMSPE_mspeFHjack`, Y, X, D, method)
}

mspeFHmcjack <- function(Y, X, D, K = 50L, method = 2L) {
    .Call(`_saeMSPE_mspeFHmcjack`, Y, X, D, K, method)
}

mspeFHpb <- function(Y, X, D, K = 50L) {
    .Call(`_saeMSPE_mspeFHpb`, Y, X, D, K)
}

mspeFHsumca <- function(Y, X, D, K = 50L, method = 2L) {
    .Call(`_saeMSPE_mspeFHsumca`, Y, X, D, K, method)
}

